### ISSUE TITLE
Add ability to put non-Glitter routes/apps/functionality into the menu and pages hierarchy

### ISSUE THREAD

**Issue by takeontom** [blancltd/django-glitter#69]
If I create a non-Glitter app, with its own views, URL routes, etc. and place it within a Glitter site, I currently can't get Glitter to recognise my non-Glitter app's URLs, allow the user to set the URL of my app via Glitter's admin functionality, etc.

For example, I can't [nicely] do the following:

* Make my custom app a sub-page of an existing Glitter page and URL
* Select any of my custom app's URL routes from a list of pages on the site (e.g. for setting up Call To Action URLs on a custom Glitter Block)
* Add my custom app to the primary nav

DjangoCMS has the concept of "apphooks", which solves all the above problems: http://docs.django-cms.org/en/stable/how_to/apphooks.html

The basic concept is that a special CMS page can be created, which sits within the CMS's page structure, nav, etc. When accessed, this special page is configured to load up the non-DjangoCMS app, as if you were accessing that app's `/` URL route.

Then through the default template behaviour in Django, the app can appear seamlessly in a DjangoCMS app.

**Comment by tomkins** [comment]
There's a few ways of doing this with glitter pages - although it assume glitter pages is the main thing powering navigation.

Probably worth going over it at some point.
